services:
  jz-admin:
    image: docker-registry.codehype.tech/jz-admin:latest
    platform: linux/amd64
    env_file: ./.env
    ports:
      - 4010:3010
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    restart: always
  jz-customer:
    image: docker-registry.codehype.tech/jz-customer:latest
    platform: linux/amd64
    env_file: ./.env
    ports:
      - 4020:3020
    build:
      context: .
      dockerfile: ./customer/Dockerfile
    restart: always
  jz-technician:
    image: docker-registry.codehype.tech/jz-technician:latest
    platform: linux/amd64
    env_file: ./.env
    ports:
      - 4030:3030
    build:
      context: .
      dockerfile: ./technician/Dockerfile
    restart: always